name: Usage

on:
  issue_comment:
    types:
      - created

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/chatgpt-bot@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}